- name: Include emailoauth2proxy role
  include_role:
    name: emailoauth2proxy

- name: Install dependencies
  become: true
  package:
    name: isync

- name: Create store directories
  file:
    path: "~/{{item}}"
    state: directory
  loop: "{{emails | select(\"search\", \"@hotmail\\.com$\")}}"
- name: Render configuration
  template:
    src: mbsyncrc.hotmail.j2
    dest: ~/.mbsyncrc
