---
- name: Configure 'pureos'
  hosts: localhost
  tasks:
    - name: Configure git
      git_config:
        name: "{{item.name}}"
        scope: global
        value: "{{item.value}}"
      with_items:
        - name: user.name
          value: "{{name}}"
        - name: user.email
          value: "{{email}}"
    - name: Configure bash
      lineinfile:
        path: ~/.bashrc
        line: export EDITOR=vim
