- name: Configure git
  git_config:
    name: "{{item.name}}"
    scope: global
    value: "{{item.value}}"
  with_items:
  - name: credential.helper
    value: store
  - name: user.name
    value: "{{name}}"
  - name: user.email
    value: "{{email}}"

- name: Create git config dir
  file:
    path: ~/.config/git
    state: directory

- name: Configure gitignore
  copy:
    src: ignore
    dest: ~/.config/git/ignore

- name: Configure git credentials
  template:
    src: git-credentials
    dest: ~/.git-credentials
    mode: 0600
  when: git_credentials | default
