- name: Configure git
  git_config:
    name: "{{item.name}}"
    scope: global
    value: "{{item.value}}"
  with_items:
    - name: user.name
      value: "{{name}}"
    - name: user.email
      value: "{{email}}"

- name: Create git config dir
  file:
    path: ~/.config/git
    state: directory

- name: Configure gitignore
  copy:
    src: ignore
    dest: ~/.config/git/ignore
